### PR TITLE
[WIP] Remove recipe which overlay other recipes in upper layers

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by Herrie82** [comment]
@tofee lgvl is used for your PP recovery no? I have no objections in general, however I didn't build test this at my end yet for PPP.

**Comment by shr-project** [comment]
I think this was WIP and more changes were needed as discussed with Tofee on IRC, let me check the history.

**Comment by Herrie82** [comment]
I'm getting this for PPP while building:
/lv_conf.h: No such file or directory
|    41 | #    include "../../lv_conf.h"                 /*Else assume lv_conf.h is next to the lvgl folder*/

**Comment by Tofee** [comment]
Migrating to a newer LVGL version will be a bit of work, so just removing the recipe version won't help much here

**Comment by shr-project** [comment]
Merged though https://github.com/webOS-ports/meta-pine64-luneos/pull/33 and apitrace from here.

**Pull request closed without merging**
